### PR TITLE
[mod] README.md

### PR DESCRIPTION
**Pull request by sachaos**
Your plug-in is so good.
I modified option name in README.

`nameTemplate` -> `pathTemplate`

Thank you.

### CODE REVIEW

**Comment by sachaos** [comment]
Thank you for reply.

OK, I understood.
But, I think README.md is wrong.

Actually, If I use `nameTemplate` option as of README.md, that will not work correctly.
So I read the source code, I tried to explore the cause.
Then, I found to work correctly by changing `nameTemplate` to `pathTemplate`.
So, I modified README.md.

Thank you.

**Comment by timnew** [comment]
Oh, god, sorry my bad....
I'm hesitating between the `nameTemplate` and `pathTemplate` when I was writing the code. And finally I decided to use nameTemplate, but maybe I forgot to update the code.
@sachaos I'll merge you pull request....

**Comment by sachaos** [comment]
Thank you! :)

**Comment by timnew** [comment]
No, thank you :smiley:

**Pull request merged**
